Feat/crud usuario
willsantos/OA_backend_core pull request #14
Opened 2023-08-25 10:22 UTC by Phses

Criei as entidades da aplicação de acordo com o banco de dados (database first)
Criei os contratos Request e Response
Fiz um CRUD básico de usuario, sem implementar questões de segurança e envio de email.

2023-08-25 13:21 UTC, willsantos requested changes

2023-08-25 13:21 UTC, willsantos commented on OpenAcademy.sql
Ficou perfeito isso

2023-08-25 13:21 UTC, willsantos commented on OA_Core.Api/Controllers/UsuarioController.cs
Faltou fazer os tratamentos por try Catch

2023-08-25 13:21 UTC, willsantos commented on OA_Core.Api/Controllers/UsuarioController.cs
Vamos mover o mapper para a camada de serviço, deixar a controle apenas pra capturar as exceptions e devolver as infos para o usuário.

2023-08-25 14:25 UTC, willsantos commented on OA_Core.Api/Controllers/UsuarioController.cs
[discutido em reunião]

Vamos utilizar o padrão de notifications em vez de exceptions

2023-08-29 20:56 UTC, Phses commented on OA_Core.Api/Controllers/UsuarioController.cs
Fiz as alterações pedidas.

2023-08-29 21:18 UTC, willsantos approved these changes
Muito divertido esse tal de Notification

2023-08-30 12:19 UTC, gabrielacalcabrine commented on OpenAcademy.sql
concordo. Odeio ternário mas agora tô pensando em usar tb. Fica tão 'munitinho'

2023-08-30 12:23 UTC, gabrielacalcabrine approved these changes

2023-08-30 12:24 UTC, merged