Feat/crud professor
willsantos/OA_backend_core pull request #19
Opened 2023-08-31 19:18 UTC by gabrielacalcabrine

#6 
 Crud camadas Professor. Faltam validações

2023-08-31 19:37 UTC, Edileal approved these changes

2023-09-01 12:35 UTC, willsantos requested changes

2023-09-01 12:35 UTC, willsantos commented on OA_Core.Repository/Repositories/ProfessorRepository.cs
> +        public async Task<IEnumerable<Professor>> ListPaginationAsync(int page, int rows)
Está retornado ID duplicado tanto pra professor quanto usuario

2023-09-01 12:38 UTC, willsantos approved these changes

2023-09-01 12:47 UTC, merged