feat/CRUD-Aluno
willsantos/OA_backend_core pull request #21
Opened 2023-09-01 18:03 UTC by Edileal

# feat/CRUD-Aluno

## Descrição

Implementação básica do cadastro de alunos sem verificações de segurança na plataforma Open Academy.
Foi feita toda a estrutura necessária para a implementação através das camadas services, controllers, domain e repository.
Foi utilizado SQL para salvar os dados no banco.

Fixes #5 

## Como testar

- Faça o checkout dessa branch: `git checkout nome-da-branch`
- Instale as dependências: `dotnet restore`
- Rode os testes: `dotnet run`
- Verifique se o resultado é o esperado.

## Checklist

Antes de enviar o PR, verifique se você completou os seguintes itens:

- [x] Eu li as [diretrizes de contribuição](#) do projeto.
- [x] Eu adicionei testes que provam que a minha solução funciona.
- [x] Eu atualizei a documentação conforme necessário.
- [x] Eu revisei o meu próprio código e corrigi os erros de estilo.
- [x] Eu solicitei a revisão de pelo menos dois outros colaboradores.

2023-09-01 18:19 UTC, willsantos requested changes
Agora só precisa mudar de Dapper para Entity

2023-09-05 14:46 UTC, willsantos approved these changes

2023-09-05 14:57 UTC, gabrielacalcabrine commented on OA_Core.Domain/Entities/Aluno.cs
> +            Id = Guid.Parse(id);
creio que não precise mais desse parse aqui

2023-09-05 15:02 UTC, gabrielacalcabrine requested changes

2023-09-05 15:02 UTC, gabrielacalcabrine commented on OA_Core.Domain/Validations/AlunoValidator.cs
> +            RuleFor(u => u.UsuarioId)
acrescentar validações

2023-09-05 15:02 UTC, gabrielacalcabrine commented on OA_Core.Repository/Repositories/AlunoRepository.cs
> +                new MySqlParameter("@usuario_id", aluno.UsuarioId),
edity não precisa de passar usuarioid pelo request. Sugiro criar um novo request pra o put e acrescentar um construtor a mais sem passar a guid de usuario.

2023-09-05 15:02 UTC, gabrielacalcabrine commented on OA_Core.Service/AlunoService.cs
> +            entity.DataCriacao = find.DataCriacao;
aqui vc acrescentaria isso após a mudança do request para o put:
entity.Usuarioid = find.UsuarioId;
assim ele pega o valor de usuarioId do banco

2023-09-05 17:00 UTC, gabrielacalcabrine approved these changes

2023-09-05 17:01 UTC, Edileal commented on OA_Core.Domain/Validations/AlunoValidator.cs
> +            RuleFor(u => u.UsuarioId)
subirei um pr só para isso

2023-09-05 17:02 UTC, gabrielacalcabrine approved these changes

2023-09-05 17:02 UTC, Edileal commented on OA_Core.Repository/Repositories/AlunoRepository.cs
> +                new MySqlParameter("@usuario_id", aluno.UsuarioId),
Retirado. Quando tiver um campo específico de aluno será implementado o put.

2023-09-05 17:03 UTC, willsantos approved these changes

2023-09-05 17:04 UTC, Edileal commented on OA_Core.Service/AlunoService.cs
> +            entity.DataCriacao = find.DataCriacao;
Isso. Mas por enquanto está sem implementação. Aguardando o novo campo.

2023-09-05 17:05 UTC, merged