Feat/upload image
willsantos/OA_backend_core pull request #54
Opened 2023-09-18 17:01 UTC by mabeldev

# Upload de imagem

## Descrição

Feita classe para realizar upload de imagem via DataForm

## Issue relacionada

Fixes #52 - Upload de imagem

## Como testar

- Faça o checkout dessa branch: `git checkout nome-da-branch`
- Instale as dependências: `dotnet restore`
- Rode os testes: `dotnet run`
- Verifique se o resultado é o esperado.

Envio da foto deve ser realizado via Postman com a seguinte configuração:
![image](https://github.com/willsantos/OA_backend_core/assets/116887689/f5a7c5dd-dd83-4759-830c-dd50b26b3b47)

O resultado será o seguinte:
![image](https://github.com/willsantos/OA_backend_core/assets/116887689/8c8404e1-7509-4993-8106-9512d67a7994)

## Checklist

Antes de enviar o PR, verifique se você completou os seguintes itens:

- [x] Eu li as [diretrizes de contribuição](#) do projeto.
- [x] Eu adicionei testes que provam que a minha solução funciona.
- [ ] Eu atualizei a documentação conforme necessário.
- [x] Eu revisei o meu próprio código e corrigi os erros de estilo.
- [x] Eu solicitei a revisão de pelo menos dois outros colaboradores.

2023-09-18 19:31 UTC, gabrielacalcabrine requested changes
Colocar no padrão as exceções retirarando o try cath

2023-09-19 16:05 UTC, gabrielacalcabrine approved these changes

2023-09-19 18:41 UTC, willsantos approved these changes

2023-09-19 18:41 UTC, willsantos commented on OA_Core.Service/ImagemService.cs
> +			// Combine o caminho completo do arquivo.
Evite de colocar comentários que explicam o código que é obvio :)

2023-09-19 19:40 UTC, merged