feat/criarRepositoryBase
willsantos/OA_backend_core pull request #55
Opened 2023-09-18 17:45 UTC by Edileal

# feat/criarRepositoryBase

## Descrição

Criação da base repository;

## Issue relacionada

#48 

## Como testar

- Faça o checkout dessa branch: `git checkout nome-da-branch`
- Instale as dependências: `dotnet restore`
- Rode os testes: `dotnet run`
- Verifique se o resultado é o esperado.

## Checklist

Antes de enviar o PR, verifique se você completou os seguintes itens:

- [x] Eu li as [diretrizes de contribuição](#) do projeto.
- [ ] Eu adicionei testes que provam que a minha solução funciona.
- [ ] Eu atualizei a documentação conforme necessário.
- [x] Eu revisei o meu próprio código e corrigi os erros de estilo.
- [x] Eu solicitei a revisão de pelo menos dois outros colaboradores.

2023-09-18 19:38 UTC, gabrielacalcabrine approved these changes

2023-09-19 12:40 UTC, gabrielacalcabrine requested changes
Esqueceu a paginação

2023-09-19 12:59 UTC, mabeldev requested changes

2023-09-19 12:59 UTC, mabeldev commented on OA_Core.Repository/Repositories/BaseRepository.cs
> +				throw new Exception(ex.Message);
Aqui e nos demais métodos, imagino que o ideal seria jogar a classe de notificação que esta sendo usado nos demais locais da aplicação, pra seguir o padrão do projeto, o que vc acha?

2023-09-19 16:41 UTC, gabrielacalcabrine approved these changes

2023-09-19 16:42 UTC, gabrielacalcabrine requested changes
atualize a branch

2023-09-19 16:46 UTC, gabrielacalcabrine approved these changes

2023-09-19 16:48 UTC, gabrielacalcabrine approved these changes

2023-09-19 17:17 UTC, mabeldev approved these changes

2023-09-19 18:13 UTC, merged