Feat/refatorar testes controller
willsantos/OA_backend_core pull request #78
Opened 2023-09-26 14:46 UTC by Edileal

# Título do PR

## Descrição

Todos os testes da controller alterados

## Issue relacionada

Fixes #75 

## Como testar

Descreva os passos para testar as alterações propostas por esse PR. Por exemplo:

- Faça o checkout dessa branch: `git checkout nome-da-branch`
- Instale as dependências: `dotnet restore`
- Rode os testes: `dotnet run`
- Verifique se o resultado é o esperado.

## Checklist

Antes de enviar o PR, verifique se você completou os seguintes itens:

- [x] Eu li as [diretrizes de contribuição](../docs/CONTRIBUTING.md) do projeto.
- [x] Eu adicionei testes que provam que a minha solução funciona.
- [ ] Eu atualizei a documentação conforme necessário.
- [x] Eu revisei o meu próprio código e corrigi os erros de estilo.
- [x] Eu solicitei a revisão de pelo menos dois outros colaboradores.

2023-09-26 14:59 UTC, mabeldev requested changes

2023-09-26 14:59 UTC, mabeldev commented on OA_Core.Tests/Controller/AulaControllerTest.cs
> +            //var actionResult = Assert.IsType<CreatedResult>(controllerResult); outra possibilidade
Remover linha de código comentada

2023-09-26 15:09 UTC, willsantos requested changes

2023-09-26 15:09 UTC, willsantos commented on OA_Core.Tests/Controller/AlunoControllerTest.cs
Isso não estava nas diretrizes, mas colocarei:

Adiciona uma trait para a classe pelo menos

2023-09-26 15:10 UTC, willsantos commented on OA_Core.Tests/Controller/AlunoControllerTest.cs
erro meu./

2023-09-26 18:54 UTC, willsantos approved these changes

2023-09-27 12:22 UTC, mabeldev approved these changes

2023-09-27 12:24 UTC, merged